package be.uantwerpen.group1.systemy.node;

import java.io.Serializable;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;

/**
 * FileRecord class, used by the replicators. Generated by the nodes making the ownership assignment, rather
 * than the actual file owners themselves. The latter is a design choice.
 *
 * @author Abdil Kaya
 */
public class FileRecord implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 2434639336708225548L;
	private String fileName;
	private List<String> downloadedByNodes = new ArrayList<String>();
	private String localByNode;

	public FileRecord(String fileName, String sentToNode, String localByNode)
	{
		this.fileName = fileName;
		this.localByNode = localByNode;
		downloadedByNodes.add(sentToNode);
	}

	public void addDownloadedBy(String nodeIP)
	{
		if (!downloadedByNodes.contains(nodeIP))
			downloadedByNodes.add(nodeIP);
	}

	public String getFileName()
	{
		return fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

	public List<String> getDownloadedByNodes()
	{
		return downloadedByNodes;
	}

	public void setDownloadedByNodes(List<String> downloadedByNodes)
	{
		this.downloadedByNodes = downloadedByNodes;
	}

	public String getLocalByNode()
	{
		return localByNode;
	}

	public void setLocalByNode(String localByNode)
	{
		this.localByNode = localByNode;
	}
}
